# Generated by Django 5.0.3 on 2024-05-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0003_loginform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenMuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenesMuelle/')),
            ],
        ),
    ]
