# Generated by Django 5.0.3 on 2024-05-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0004_imagenmuelle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenmuelle',
            old_name='imagen',
            new_name='imagen_muelle',
        ),
    ]
