# Generated by Django 5.0.3 on 2024-07-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0005_rename_imagen_imagenmuelle_imagen_muelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imagen_card', models.ImageField(upload_to='card/')),
            ],
        ),
    ]
