# Generated by Django 5.0.3 on 2024-08-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0006_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='imagen',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
