# Generated by Django 5.0.3 on 2024-08-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0009_card_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenOtroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_otroCard', models.ImageField(upload_to='imagenesMuelle/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
