# Generated by Django 5.0.3 on 2024-08-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0010_imagenotrocard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenotrocard',
            name='imagen_otroCard',
            field=models.ImageField(upload_to='imagenesOtroCard/'),
        ),
    ]
